### ISSUE TITLE
Bug: inconsistent date formatting in feed listing

### ISSUE THREAD

**Issue by billglover** [billglover/starling-cli#39]
When a transaction timestamp is a whole number of seconds, the fraction component is not displayed causing the columns to misalign in the feed listings. this issue is largely present for internal transactions, but there is no obvious reason why this would be limited to the timestamps for internal transactions.

*Current behaviour:*
```plain
004 2018-07-03 12:47:02.883 +0000 UTC   16.00      MASTER_CARD...
005 2018-07-02 00:04:49 +0000 UTC       50.00      FASTER_PAYMENTS_IN...
```

*Desired behaviour:*
```plain
004 2018-07-03 12:47:02.883 +0000 UTC   16.00      MASTER_CARD...
005 2018-07-02 00:04:49.000 +0000 UTC   50.00      FASTER_PAYMENTS_IN...
```

**Comment by alimasyhur** [comment]
I created a new pull request for this bug.
I added default time format, and make the feed listing item follows the format.

**Comment by billglover** [comment]
Thanks Ali, I'll try and take a look at merging this evening.
